# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import dborgproto_pb2 as dborgproto__pb2


class DashborgServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConnectClient = channel.unary_unary(
                '/dashborg.rpc1.DashborgService/ConnectClient',
                request_serializer=dborgproto__pb2.ConnectClientMessage.SerializeToString,
                response_deserializer=dborgproto__pb2.ConnectClientResponse.FromString,
                )
        self.RequestStream = channel.unary_stream(
                '/dashborg.rpc1.DashborgService/RequestStream',
                request_serializer=dborgproto__pb2.RequestStreamMessage.SerializeToString,
                response_deserializer=dborgproto__pb2.RequestMessage.FromString,
                )
        self.SendResponse = channel.unary_unary(
                '/dashborg.rpc1.DashborgService/SendResponse',
                request_serializer=dborgproto__pb2.SendResponseMessage.SerializeToString,
                response_deserializer=dborgproto__pb2.SendResponseResponse.FromString,
                )
        self.SetPath = channel.unary_unary(
                '/dashborg.rpc1.DashborgService/SetPath',
                request_serializer=dborgproto__pb2.SetPathMessage.SerializeToString,
                response_deserializer=dborgproto__pb2.SetPathResponse.FromString,
                )
        self.RemovePath = channel.unary_unary(
                '/dashborg.rpc1.DashborgService/RemovePath',
                request_serializer=dborgproto__pb2.RemovePathMessage.SerializeToString,
                response_deserializer=dborgproto__pb2.RemovePathResponse.FromString,
                )
        self.FileInfo = channel.unary_unary(
                '/dashborg.rpc1.DashborgService/FileInfo',
                request_serializer=dborgproto__pb2.FileInfoMessage.SerializeToString,
                response_deserializer=dborgproto__pb2.FileInfoResponse.FromString,
                )
        self.ConnectLink = channel.unary_unary(
                '/dashborg.rpc1.DashborgService/ConnectLink',
                request_serializer=dborgproto__pb2.ConnectLinkMessage.SerializeToString,
                response_deserializer=dborgproto__pb2.ConnectLinkResponse.FromString,
                )


class DashborgServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ConnectClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemovePath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DashborgServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConnectClient': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectClient,
                    request_deserializer=dborgproto__pb2.ConnectClientMessage.FromString,
                    response_serializer=dborgproto__pb2.ConnectClientResponse.SerializeToString,
            ),
            'RequestStream': grpc.unary_stream_rpc_method_handler(
                    servicer.RequestStream,
                    request_deserializer=dborgproto__pb2.RequestStreamMessage.FromString,
                    response_serializer=dborgproto__pb2.RequestMessage.SerializeToString,
            ),
            'SendResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.SendResponse,
                    request_deserializer=dborgproto__pb2.SendResponseMessage.FromString,
                    response_serializer=dborgproto__pb2.SendResponseResponse.SerializeToString,
            ),
            'SetPath': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPath,
                    request_deserializer=dborgproto__pb2.SetPathMessage.FromString,
                    response_serializer=dborgproto__pb2.SetPathResponse.SerializeToString,
            ),
            'RemovePath': grpc.unary_unary_rpc_method_handler(
                    servicer.RemovePath,
                    request_deserializer=dborgproto__pb2.RemovePathMessage.FromString,
                    response_serializer=dborgproto__pb2.RemovePathResponse.SerializeToString,
            ),
            'FileInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.FileInfo,
                    request_deserializer=dborgproto__pb2.FileInfoMessage.FromString,
                    response_serializer=dborgproto__pb2.FileInfoResponse.SerializeToString,
            ),
            'ConnectLink': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectLink,
                    request_deserializer=dborgproto__pb2.ConnectLinkMessage.FromString,
                    response_serializer=dborgproto__pb2.ConnectLinkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dashborg.rpc1.DashborgService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DashborgService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConnectClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dashborg.rpc1.DashborgService/ConnectClient',
            dborgproto__pb2.ConnectClientMessage.SerializeToString,
            dborgproto__pb2.ConnectClientResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/dashborg.rpc1.DashborgService/RequestStream',
            dborgproto__pb2.RequestStreamMessage.SerializeToString,
            dborgproto__pb2.RequestMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dashborg.rpc1.DashborgService/SendResponse',
            dborgproto__pb2.SendResponseMessage.SerializeToString,
            dborgproto__pb2.SendResponseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dashborg.rpc1.DashborgService/SetPath',
            dborgproto__pb2.SetPathMessage.SerializeToString,
            dborgproto__pb2.SetPathResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemovePath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dashborg.rpc1.DashborgService/RemovePath',
            dborgproto__pb2.RemovePathMessage.SerializeToString,
            dborgproto__pb2.RemovePathResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FileInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dashborg.rpc1.DashborgService/FileInfo',
            dborgproto__pb2.FileInfoMessage.SerializeToString,
            dborgproto__pb2.FileInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConnectLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dashborg.rpc1.DashborgService/ConnectLink',
            dborgproto__pb2.ConnectLinkMessage.SerializeToString,
            dborgproto__pb2.ConnectLinkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
